modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="rpg_attribute_system"
version="2.0.0"
displayName="RPG Attribute System"
displayURL="https://www.nightbeam.cloud"
logoFile="logo.png"
credits="thank you : @porogulaemeo"
authors="NAIZO"
description="A lightweight RPG-style system that scales player attributes based on level."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.rpg_attribute_system]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.rpg_attribute_system]]
modId="jauml"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.rpg_attribute_system]]
modId="jauml"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
# End of user code block dependencies configuration
